name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3a2c85b1bcbe4ca7c31c5c840a4eaeeaf96db52b9cce620c1bce3f6051ec52b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
