name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45b6250a6ba1571f0c3ac02014a3e78835cd26383412ede31115e7992703ec4c"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
