name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c622e4a0f0ebf713aba6144515a8bd564dd3dea8c64db46082b67e1631f6d3e"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
