name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85839177521ad9e8940241ae83eb7e45d7127a80c8d133dd0210b85df0562f32"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
