name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecd97844cde6aff00b535339682982db97a9aef2d0b1a39a02692c0851963e7e"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
