name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5669688b23ae5b2d513f3e64f2bb432960894661c7efb0352896f618c8c3fe8"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
