name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0027f71f5667dd4eb9336b2e0ab38950bdeafd15d9ce27a27ec3413dbb9b26f8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
