name = "Crowpack Expert"
author = "crow-maki"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89647582f17e1fe47a220bddcd37e3010b9c3913315cdf4a65c5ffe463c6af38"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
